include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # You can add custom lint rules here if needed.
    # For example:
    # prefer_const_constructors: true

analyzer:
  exclude:
    - packages/media_kit_patched/**
    - packages/video_player_android_patched/**
    - tmp_play.dart
